"""empty message

Revision ID: 3612d2f9a317
Revises: 
Create Date: 2021-09-24 19:09:32.629349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3612d2f9a317'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desserts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='desserts_pkey')
    )
    op.create_table('entrees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meat', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('side_1', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('side_2', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entrees_pkey')
    )
    # ### end Alembic commands ###

def downgrade():
    
    op.drop_table('entrees')
    op.drop_table('desserts')
    # ### end Alembic commands ###
