"""empty message

Revision ID: 6bc88dab09e0
Revises: a439cd93701e
Create Date: 2021-09-24 18:14:21.716328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc88dab09e0'
down_revision = 'a439cd93701e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dessert')
    op.drop_table('entree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entree',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meat', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('side_1', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('side_2', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entree_pkey')
    )
    op.create_table('dessert',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dessert_pkey')
    )
    # ### end Alembic commands ###
