"""empty message

Revision ID: a439cd93701e
Revises: 
Create Date: 2021-09-24 18:12:16.234962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a439cd93701e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Entree')
    op.drop_table('Dessert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dessert',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Dessert_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Dessert_pkey')
    )
    op.create_table('Entree',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Entree_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('meat', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('side_1', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('side_2', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Entree_pkey')
    )
    # ### end Alembic commands ###
